### ISSUE TITLE
step is not quite clear

### ISSUE THREAD

**Issue by tlkao01** [DevifyPlatform/devify-server#8]
after run "node server,js"
WoT/CoAP server is listening at coap://192.168.1.110:8000
but nothing happen. the console log didn;t show any. the example don't have object and ID, how can the server print the result??

and  when to run the "node coap-view-data.js"  server.js already in running?
and what will happen after run "node coap-view-data.js"??

**Comment by jollen** [comment]
Please refer to [101-air-quality-sensor-console-print](https://github.com/DevifyPlatform/devify-server/tree/master/templates/101-air-quality-sensor-console-print). Read the doc carefully.
